apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Saha-manager bileşeni için kaynaklar
resources:
- deployment.yaml
- service.yaml
- route.yaml

# 2. Ortak labels
labels:
- pairs:
    app: saha-manager
    component: saha-manager
