apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Pre-prod ortamı için tüm bileşenler
resources:
- ../../../components/saha-manager/base
- ../../../components/saha-web/base
- ../../../components/saha-sync/base
- ../../../components/saha-pars/base

# 2. Pre-prod ortamı için isim önek/soneki
namePrefix: preprod-
nameSuffix: -preprod

# 3. Pre-prod ortamı replika değerleri
replicas:
- name: saha-manager
  count: 2
- name: saha-web
  count: 1
- name: saha-sync
  count: 2
- name: saha-pars
  count: 2

# 4. Pre-prod ortamı labels
labels:
- includeSelectors: true
  pairs:
    environment: pre-prod
    scenario: staged
