apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. resources altında bu komponent için temel kaynaklar listelenir.
resources:
- deployment.yaml
- service.yaml
- route.yaml

# 2. labels, tüm kaynaklara eklenerek izleme ve seçicilerde kullanılabilir.
labels:
- pairs:
    app: repo-template1
    component: service-a
