apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Database komponenti tek deployment kaynağı içerir.
resources:
- deployment.yaml

# 2. Etiketler, bu komponentin kaynaklarına uygulanır.
labels:
- pairs:
    app: repo-template1
    component: database
