apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Worker komponenti için deployment ve service kaynakları.
resources:
- deployment.yaml
- service.yaml

# 2. labels, worker kaynaklarına ortak etiket ekler.
labels:
- pairs:
    app: repo-template1
    component: worker
