apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. OpenShift'e özgü kaynakları burada toplar.
resources:
- deploymentconfig.yaml
- imagestream.yaml
- service.yaml
- route.yaml

# 2. labels, tüm OpenShift kaynaklarına ortak etiket ekler.
labels:
- pairs:
    app: repo-template1
    component: ocp-app
