apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Bu kök kustomization, tüm bileşen tabanlarını birleştirir.
resources:
- components/service-a/base
- components/service-b/base
- components/service-c/base
- components/worker/base
- components/database/base
- components/cronjob/base
- components/ocp-app/base

# 2. Buradan kube/kustomize çıktısını oluşturmak için root dizine bakabilirsiniz.
#    Örnek: kubectl kustomize repo-template1
