apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-index-html
data:
  index.html: |
    <html>
      <head><title>repo-gultekin Apache</title></head>
      <body>
        <h1>Apache Web Sunucusu - repo-gultekin</h1>
        <p>OpenShift Kustomize ile dağıtıldı.</p>
      </body>
    </html>
