apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. service-c için temel kaynakları burada listeliyoruz.
resources:
- deployment.yaml
- service.yaml
- route.yaml

# 2. labels, burada bu komponente ait ortak etiketleri ekler.
labels:
- pairs:
    app: repo-template1
    component: service-c
