apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. resources bu komponentin deployment, servis ve route kaynaklarını içerir.
resources:
- deployment.yaml
- service.yaml
- route.yaml

# 2. labels, bu komponent için ortak etiketler ekler.
labels:
- pairs:
    app: repo-template1
    component: service-b
