apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../components/web/base
- ../../../components/api/base
- ../../../components/db/base

namePrefix: preprod-
nameSuffix: -preprod

replicas:
- name: web
  count: 2
- name: api
  count: 2

labels:
- includeSelectors: true
  pairs:
    environment: pre-prod
    tier: backend
